All resources - add to NamespaceRoots, NamespaceFolders, Add ReplicationGroups, Connections & Memberships
dsccommunity/DFSDsc pull request #126
Opened 2022-10-20 17:20 UTC by Borgquite

#### Pull Request (PR) description

New functionality and fixes for resources:

- Add support for setting a DFS Namespace root target's referral status (TargetState) to be either `Online` or `Offline`
  in DSC_DFSNamespaceRoot (replaces PR #97, adding tests)
- Add support for setting a DFS Namespace folder target's referral status (TargetState) to be either `Online` or `Offline`
  in DSC_DFSNamespaceFolder (replaces PR #97 adding tests)
- Add DSC_DFSReplicationGroupMember module allowing replication group members to be separately defined outside of DFSReplicationGroup
  - This allows situations where new memberships may be added through DSC Configurations on each server, instead of a single server
- Allow Get-TargetResource and Test-TargetResource to be run in DSC_DFSReplicationGroupFolder and DSC_DFSReplicationGroupMember without errors even if the replication group does not yet exist - Fixes [Issue #125](https://github.com/dsccommunity/DFSDsc/issues/125)
- Add support for CrossFileRDCEnabled and MinimumRDCFileSizeInKB parameters in DSC_DFSReplicationGroupConnection resource
- Add support for EnsureEnabled, MinimumFileStagingSize, ConflictAndDeletedQuotaInMB, RemoveDeletedFiles and DfsnPath parameters in DSC_DFSReplicationGroupMembership resource
- Converted all 'Ensure' parameters to default to 'Present' - Fixes [Issue #29](https://github.com/dsccommunity/DFSDsc/issues/29)
- Add support for modifying Namespace Root and Folder ReferralStatus (State) - Fixes [Issue #96](https://github.com/dsccommunity/DFSDsc/issues/96)
- Various other fixes to tests along the way

Sorry for the bulk PR but wasn't sure how to fix #29 otherwise at the same time as adding new resources.

#### This Pull Request (PR) fixes the following issues

- Fixes #29 
- Fixes #96 
- Fixes #125 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dfsdsc/126)

2022-10-20 18:33 UTC, Borgquite commented
Am aware of failing tests, will work on tomorrow

2022-10-21 15:04 UTC, Borgquite commented
Closing & re-opening to reinitiate tests

2022-10-24 09:30 UTC, Borgquite commented
@gaelcolas @PlagueHO Can you review this please? (The 'code-review/reviewable' test appears to have hanged - perhaps due to the bug below?

https://github.com/Reviewable/Reviewable/issues/655

2022-10-25 04:54 UTC, PlagueHO commented
Hi @Borgquite. We use Reviewable to perform the code review. It'll report the state once we complete the review. So, it looks like it is good to review right?

2022-10-25 06:10 UTC, Borgquite commented
Hi @PlagueHO,
Understood. Yes - should be ready for review! :)

2022-10-26 07:00 UTC, PlagueHO commented
Cool. Am hoping to get into it Friday night. Thanks for submitting!

2022-11-05 19:59 UTC, PlagueHO requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126)* status: 0 of 60 files reviewed, 2 unresolved discussions (waiting on @Borgquite)

___
*[`CHANGELOG.md` line 10 at r5](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NG8M1fL7gvbuvLi65cG:-NG8M1fL7gvbuvLi65cH:b9ip2d1) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/1bb0c2773c03298b65b5221f5b8f6c8bab0f9d6e/CHANGELOG.md#L10)):*
> ```Markdown
> ### Changed
> 
> - Add support for setting a DFS Namespace root target's referral status (TargetState) to be either `Online` or `Offline`
> ```

Is it possible to separate these changelog entries into sections for each resource (like we've started doing with other resources). E.g., https://github.com/dsccommunity/ComputerManagementDsc/blob/main/CHANGELOG.md#added-1

```md
- DFSNamespaceRoot
  - Change 1
  - Change 2
- DFSReplicationGroupMember
  - Change 3
  - Change 4
```
___
*[`CHANGELOG.md` line 20 at r5](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NG8MyvN3xZb8r2a-Iia:-NG8MyvN3xZb8r2a-Iib:bbma2qt) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/1bb0c2773c03298b65b5221f5b8f6c8bab0f9d6e/CHANGELOG.md#L20)):*
> ```Markdown
> - Add support for CrossFileRDCEnabled and MinimumRDCFileSizeInKB parameters in DSC_DFSReplicationGroupConnection resource.
> - Add support for EnsureEnabled, MinimumFileStagingSize, ConflictAndDeletedQuotaInMB, RemoveDeletedFiles and DfsnPath parameters in
>   DSC_DFSReplicationGroupMembership resource.
> ```

Hi @borgquite, in the commits, it is mentioned that there is a BREAKING CHANGE. But it doesn't look like this is mentioned in the CHANGELOG. We'd need to add that to any changes to force a new major version number.


<!-- Sent from Reviewable.io -->

2022-11-07 12:56 UTC, Borgquite commented
@PlagueHO

> Is it possible to separate these changelog entries into sections for each resource (like we've started doing with other resources). E.g., https://github.com/dsccommunity/ComputerManagementDsc/blob/main/CHANGELOG.md#added-1

Sure, done!

> Hi @Borgquite, in the commits, it is mentioned that there is a BREAKING CHANGE. But it doesn't look like this is mentioned in the CHANGELOG. We'd need to add that to any changes to force a new major version number.

This is due to the fix for #96 where I imported the PR #97. The PR code as originally imported included a breaking change because it required the parameter 'State' to be mandatory (in my code, the equivalent parameter is 'TargetState' because it is the root/folder *target* status which is being set, not the root/folder itself). However as discussed in #96 there is no particular need for this parameter to be mandatory, as long as it defaults to 'Online'. So I've changed it to avoid the breaking change.

2022-11-21 11:42 UTC, Borgquite commented
@PlagueHO Just checking if you need anything else - I think I've addressed the two remaining issues in my latest commit?

2022-11-24 18:38 UTC, PlagueHO commented
Hi @Borgquite - sorry about the delay. I've been completely swamped with my day job and book writing (and will be till 15 Dec). I'll have more time to get to this. Again, am really sorry!

2022-11-29 11:53 UTC, Borgquite commented
Hi @PlagueHO, understood - we're all volunteers here, I think! Thanks if you're able to take a look towards the end of the month.
Kind regards,
Chris

2022-12-15 17:35 UTC, Borgquite commented
Hey @PlagueHO just wondering how your availability is now & if you'll have a chance to review this? Many thanks :)
Chris

2023-01-05 12:31 UTC, Borgquite commented
Hey @PlagueHO - when do you think you'll get time to review this? Want to respect your time and not keep pestering so a timeframe would really help :) Thank you!

2023-01-12 16:59 UTC, Borgquite commented
@PlagueHO Any chance on getting this changed approved? I'm waiting on this to let us use this change in production :)

2023-01-12 19:08 UTC, PlagueHO requested changes
Hi @Borgquite - sorry about the delay on this. I'm working on it. I've made some initial comments that I think we need to sort out.

My concern will be the confusion around the naming of DFSReplicationGroupMember and DFSReplicationGroupMembership.

Is it possible for the naming to be changed to clarify how they differ? If not then we'll want to put some more info in the README.md and examples indicating how they differ and when each should be used.

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-:-NLbN5qf4Bat1ZTG0lY2:bmi1diu)* status: 1 of 60 files reviewed, 3 unresolved discussions (waiting on @Borgquite)

___
*[`CHANGELOG.md` line 20 at r5](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NG8MyvN3xZb8r2a-Iia:-NLXIWiz4JkWhP2XFwcK:b-4ngu8q) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/1bb0c2773c03298b65b5221f5b8f6c8bab0f9d6e/CHANGELOG.md#L20)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Hi @borgquite, in the commits, it is mentioned that there is a BREAKING CHANGE. But it doesn't look like this is mentioned in the CHANGELOG. We'd need to add that to any changes to force a new major version number.
</blockquote></details>

Can you add the BREAKING CHANGE: to any changes here that result in one? See https://dsccommunity.org/guidelines/contributing/#breaking-changes. We need to make sure the major version number is increased and we're specifying which resources have BREAKING CHANGES. Once you've made the change can you mark this as complete in Reviewable? That way I can figure out what is completed and what is still open. Thank you :grinning:
___
*[`CHANGELOG.md` line 16 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NLXJHOxD9vhTIct9eF1:-NLXJHOxD9vhTIct9eF2:bmhv45j) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/CHANGELOG.md#L16)):*
> ```Markdown
> - DFSNamespaceFolder
>   - Added support for setting target referral status (TargetState) - fixes [Issue #96](https://github.com/dsccommunity/DFSDsc/issues/96).
> - DFSReplicationGroupMember
> ```

Hi @Borgquite - I think we're going to run into confusion between DFSReplicationGroupMember and DFSReplicationGroupMembership.

Can we make it clear in the README.md for both of these how they differ? 


<!-- Sent from Reviewable.io -->

2023-01-16 13:21 UTC, Borgquite reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126)* status: 1 of 60 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 10 at r5](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NG8M1fL7gvbuvLi65cG:-NLuisza67zth6fHUrwq:b-r8im0m) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/1bb0c2773c03298b65b5221f5b8f6c8bab0f9d6e/CHANGELOG.md#L10)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is it possible to separate these changelog entries into sections for each resource (like we've started doing with other resources). E.g., https://github.com/dsccommunity/ComputerManagementDsc/blob/main/CHANGELOG.md#added-1

```md
- DFSNamespaceRoot
  - Change 1
  - Change 2
- DFSReplicationGroupMember
  - Change 3
  - Change 4
```
</blockquote></details>

This should be all done now.
___
*[`CHANGELOG.md` line 20 at r5](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NG8MyvN3xZb8r2a-Iia:-NLujEDb8kblBaELHPqM:b-j9e1zp) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/1bb0c2773c03298b65b5221f5b8f6c8bab0f9d6e/CHANGELOG.md#L20)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add the BREAKING CHANGE: to any changes here that result in one? See https://dsccommunity.org/guidelines/contributing/#breaking-changes. We need to make sure the major version number is increased and we're specifying which resources have BREAKING CHANGES. Once you've made the change can you mark this as complete in Reviewable? That way I can figure out what is completed and what is still open. Thank you :grinning:
</blockquote></details>

TL;DR - the changes made in my pull should mean there are no longer any breaking changes.

This is due to the fix for #96 where I imported the PR #97. The PR code as originally imported included a breaking change because it required the parameter 'State' to be mandatory (in my code, the equivalent parameter is 'TargetState' because it is the root/folder target status which is being set, not the root/folder itself). However as discussed in #96 there is no particular need for this parameter to be mandatory, as long as it defaults to 'Online'. So I've changed it to avoid the breaking change.
___
*[`CHANGELOG.md` line 16 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NLXJHOxD9vhTIct9eF1:-NLuj2ZX9V3h0YJn1Nqx:b-cg1n2q) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/CHANGELOG.md#L16)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Hi @Borgquite - I think we're going to run into confusion between DFSReplicationGroupMember and DFSReplicationGroupMembership.

Can we make it clear in the README.md for both of these how they differ? 
</blockquote></details>

Hey, I agree that the naming isn't ideal. My thinking was that it was best to reflects the underlying relevant PowerShell cmdlets (which are equally as confusing - Get-DfsrMember and Get-DfsrMembership) than invent a new naming convention.

I could certainly update README.md with a bit more clarity - perhaps:

DFSReplicationGroupMember: Configure Replication Group member computers in a replication group.
DFSReplicationGroupMembership: Configure Replication Group membership settings for member computers of a replication group.

In terms of examples I could add one to DFSReplicationGroup and update that README to try to add a little bit more about when you use the Members property and when DFSReplicationGroupMember is appropriate if that would help?

Let me know,


<!-- Sent from Reviewable.io -->

2023-01-16 13:24 UTC, Borgquite reviewed
I've tried my best to reply to this in Reviewable - but I may have got this wrong! Sorry, not used to it and it feels a little unintuitive. 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-:-NLujtoPAsXzaLOCZRN6:bhnhhqk)* status: 1 of 60 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2023-01-21 21:44 UTC, PlagueHO requested changes
I've run out of time, but I'll continue the review later today/this week. Just some minor tweaks so far.

> Reviewed 4 of 60 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-:-NMLHYvN4uEmK1LIGWfj:b8xyuhp)* status: 7 of 60 files reviewed, 10 unresolved discussions (waiting on @Borgquite)

___
*[`CHANGELOG.md` line 20 at r5](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NG8MyvN3xZb8r2a-Iia:-NMLFVMG9hMgmfoRqMxo:b-m55ggi) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/1bb0c2773c03298b65b5221f5b8f6c8bab0f9d6e/CHANGELOG.md#L20)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

TL;DR - the changes made in my pull should mean there are no longer any breaking changes.

This is due to the fix for #96 where I imported the PR #97. The PR code as originally imported included a breaking change because it required the parameter 'State' to be mandatory (in my code, the equivalent parameter is 'TargetState' because it is the root/folder target status which is being set, not the root/folder itself). However as discussed in #96 there is no particular need for this parameter to be mandatory, as long as it defaults to 'Online'. So I've changed it to avoid the breaking change.
</blockquote></details>

Oh right - so no longer a breaking change. No problem. I'll adjust process accordingly.
___
*[`CHANGELOG.md` line 16 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NLXJHOxD9vhTIct9eF1:-NMLDuZMBui6G89qRs9Q:b-a8dt77) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/CHANGELOG.md#L16)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Hey, I agree that the naming isn't ideal. My thinking was that it was best to reflects the underlying relevant PowerShell cmdlets (which are equally as confusing - Get-DfsrMember and Get-DfsrMembership) than invent a new naming convention.

I could certainly update README.md with a bit more clarity - perhaps:

DFSReplicationGroupMember: Configure Replication Group member computers in a replication group.
DFSReplicationGroupMembership: Configure Replication Group membership settings for member computers of a replication group.

In terms of examples I could add one to DFSReplicationGroup and update that README to try to add a little bit more about when you use the Members property and when DFSReplicationGroupMember is appropriate if that would help?

Let me know,
</blockquote></details>

Yeah, agree - the DFSR cmdlet naming is problematic :grinning: 

Anyway, can you apply the updates you suggested with the example? I'd say if there is a good example if should be OK.

Let's just use the README.md as is, but add an example for the DFSReplicationGroup to show a config with DFSReplicationGroupMember and DFSReplicationGroupMembership if possible.
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 23 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NMLGmiy44RNSZrW3O2D:-NMLGmiy44RNSZrW3O2E:b-3j0idu) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L23)):*
> ```PowerShell
> 
>     .PARAMETER TargetState
>     Specifies a State for the root of a DFS namespace.
> ```

Can you change to: `Specifies the state for a DFS namespace folder.`
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 143 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NMLGybc9ZblWBTYlkNz:-NMLGybc9ZblWBTYlkO-:b-u9d9nk) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L143)):*
> ```PowerShell
> 
>     .PARAMETER TargetState
>     Specifies the target's referral status.
> ```

This doesn't seem to be the right description. Can you check?
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 429 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NMLH5QC4qO7azcXAdJv:-NMLH5QC4qO7azcXAdJw:b-u9d9nk) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L429)):*
> ```PowerShell
> 
>     .PARAMETER TargetState
>     Specifies the target's referral status.
> ```

This doesn't seem to be the right description. Can you check?
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.schema.mof` line 7 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NMLGbvIE2LyF9mcp7mf:-NMLGbvIE2LyF9mcp7mg:bswlomj) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.schema.mof#L7)):*
> ```
>     [Key, Description("Specifies a path for a root target of the DFS namespace.")] String TargetPath;
>     [Write, Description("Specifies if the DFS Namespace root should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
>     [Write, Description("Specifies the target's referral status."), ValueMap{"Offline","Online"}, Values{"Offline","Online"}] String TargetState;
> ```

I think this should be: `Specifies the state for a DFS namespace folder.`
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 23 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NMLHFF51Kjy6ChDZEAz:-NMLHFF51Kjy6ChDZEB-:b-2fetmj) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L23)):*
> ```PowerShell
> 
>     .PARAMETER TargetState
>     Specifies a State for the root of a DFS namespace.
> ```

Can you change to:



_Suggestion:_
```PowerShell
Specifies the state for the root of a DFS namespace.
```
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 155 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NMLHKY674Uk8scTom5w:-NMLHKY674Uk8scTom5x:b-2fetmj) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L155)):*
> ```PowerShell
> 
>     .PARAMETER TargetState
>     Specifies a State for the root of a DFS namespace.
> ```

Can you change to:



_Suggestion:_
```PowerShell
Specifies the state for the root of a DFS namespace.
```
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 498 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NMLHSJ_0Sm51qryN_W8:-NMLHSJ_0Sm51qryN_W9:b-2fetmj) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L498)):*
> ```PowerShell
> 
>     .PARAMETER TargetState
>     Specifies a State for the root of a DFS namespace.
> ```

Can you change to:



_Suggestion:_
```PowerShell
Specifies the state for the root of a DFS namespace.
```
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.schema.mof` line 7 at r6](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NMLGIe41-p4DKnYkvaf:-NMLGIe41-p4DKnYkvag:b1thvyu) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.schema.mof#L7)):*
> ```
>     [Key, Description("Specifies a path for a root target of the DFS namespace.")] String TargetPath;
>     [Write, Description("Specifies if the DFS Namespace root should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
>     [Write, Description("Specifies a state for a root target of the DFS namespace."), ValueMap{"Offline","Online"}, Values{"Offline","Online"}]  [...]

2023-01-24 17:08 UTC, Borgquite reviewed
I've pushed up the changes you requested, although the build tests are now failing with:

Impossible to extract the name of the Mof based DSCResource, see the error: Failed to import classes from file /home/vsts/work/1/s/output/DFSDsc/5.0.0/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.schema.mof. Error Exception calling "ImportClasses" with "3" argument(s): "Unable to load shared library 'libmi' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibmi: cannot open shared object file: No such file or directory"

I'm pretty certain it's not my changes, possibly caused by https://github.com/PowerShell/PowerShell/issues/14421 ???

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-:-NMZjurFBEkQcJCrirME:bucgwsi)* status: 3 of 61 files reviewed, 10 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 20 at r5](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NG8MyvN3xZb8r2a-Iia:-NMUqCUU1ISVa7Jzy7pW:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/1bb0c2773c03298b65b5221f5b8f6c8bab0f9d6e/CHANGELOG.md#L20)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Oh right - so no longer a breaking change. No problem. I'll adjust process accordingly.
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 16 at r6](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NLXJHOxD9vhTIct9eF1:-NMZdneo52FYbIhVuO71:bjb5m1s) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/CHANGELOG.md#L16)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Yeah, agree - the DFSR cmdlet naming is problematic :grinning: 

Anyway, can you apply the updates you suggested with the example? I'd say if there is a good example if should be OK.

Let's just use the README.md as is, but add an example for the DFSReplicationGroup to show a config with DFSReplicationGroupMember and DFSReplicationGroupMembership if possible.


</blockquote></details>

Done - added example DFSReplicationGroup\5-DFSReplicationGroup_Separate_Simple_Config.ps1
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 23 at r6](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NMLGmiy44RNSZrW3O2D:-NMZeutrBS0Q1Zr4DUOi:b-o6ule7) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L23)):*
> Specifies the state for a DFS namespace folder.
Done. I agree that the description is incorrect (sorry - I think this code was imported from PR #97 so my bad for not checking it better!) - however I think it should be 'Specifies the state of the DFS namespace folder target.' since checking the code shows that this value affects the Target value of the *-DfsnFolderTarget cmdlets, not the *-DfsnFolder cmdlets. (*-DfsnFolder cannot be accessed or set by DfsDsc at present - it is always set to 'Online')
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 143 at r6](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NMLGybc9ZblWBTYlkNz:-NMZfPYtE9Six6Kkt4Wa:bivzfwo) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L143)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This doesn't seem to be the right description. Can you check?
</blockquote></details>

Done (see above)
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 429 at r6](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NMLH5QC4qO7azcXAdJv:-NMZfSGpBfP_uAZhsZON:bivzfwo) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L429)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This doesn't seem to be the right description. Can you check?
</blockquote></details>

Done (see above)
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.schema.mof` line 7 at r6](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NMLGbvIE2LyF9mcp7mf:-NMZfehSEKS_ArLzt3Ts:bivzfwo) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.schema.mof#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this should be: `Specifies the state for a DFS namespace folder.`
</blockquote></details>

Done (see above)
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 23 at r6](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NMLHFF51Kjy6ChDZEAz:-NMZge_I2-IVeZyctCYz:b4f5p5q) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L23)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to:
</blockquote></details>

Done (again, imported from PR #97), and again, I think this should be 'Specifies the state of the DFS namespace root target.' since it gets/sets/tests the Target of *-DfsnRootTarget cmdlets, not *-DfsnRoot.
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 155 at r6](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NMLHKY674Uk8scTom5w:-NMZguI21-f6jewMQmZP:bivzfwo) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L155)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to:
</blockquote></details>

Done (see above)
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 498 at r6](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NMLHSJ_0Sm51qryN_W8:-NMZgwvkC5yN5_NIP6o9:bivzfwo) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L498)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to:
</blockquote></details>

Done (see above)
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.schema.mof` line 7 at r6](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NMLGIe41-p4DKnYkvaf:-NMZgzxnDdi3s5fmaIyU:bivzfwo) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/d67bf3f921a633fcf42f79cc9bcaf953a0e8d8a3/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.schema.mof#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to: `Specifies the state ...`
</blockquote></details>

Done (see above)


<!-- Sent from Reviewable.io -->

2023-01-25 21:08 UTC, PlagueHO commented
@Borgquite - just working on the build issue. DocGeneration is failing on `ubuntu-22.04`. I have raised an issue for this. https://github.com/dsccommunity/DscResource.DocGenerator/issues/131

We may need to pin the build image for now. I'll come back to you soon.

2023-01-25 21:24 UTC, PlagueHO commented
@Borgquite - can you apply the fix I've attached to this issue: https://github.com/dsccommunity/DFSDsc/issues/127

If you wouldn't mind adding the change into the Changelog and link to issue, that will get the build working again.

2023-01-26 10:53 UTC, Borgquite reviewed
Done :)

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-:-NMhhTaS6JOqoHdUEQJ_:bmfxgaw)* status: 2 of 62 files reviewed, 10 unresolved discussions (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2023-02-14 19:15 UTC, PlagueHO commented
@Borgquite - I'll get onto this later this week. Thanks!

2023-02-20 12:26 UTC, Borgquite commented
@PlagueHO Any updates? :)

2023-02-24 03:38 UTC, PlagueHO commented
Sorry @Borgquite ! Been hectic. Trying to make time this weekend. Really appreciate your work!

2023-03-08 12:56 UTC, Borgquite commented
Hey @PlagueHO have you managed to progress this yet?

2023-03-09 17:43 UTC, PlagueHO commented
Hi @Borgquite - oh mate! I did a bunch of work in the review, but must not have published! Will go and check

2023-03-09 17:45 UTC, PlagueHO requested changes
Sorry about delay. Looking good. Some minor tweaks required. I haven't fully finished reviewing every file (ran out of time). What we'd generally recommend is a change of this size, breaking down into multiple smaller PRs (if possible). Makes it easier to review :grinning: 

> Reviewed 47 of 60 files at r2, 4 of 6 files at r4, 5 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-:-NP9_HqW0OvArNc70iBT:b1f0k3e)* status: 60 of 62 files reviewed, 35 unresolved discussions (waiting on @Borgquite)

___
*[`CHANGELOG.md` line 16 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9QD3Z2posvv2703Dy:-NP9QD3_29meGrLx_s1o:by6u731) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/CHANGELOG.md#L16)):*
> ```Markdown
> - DFSNamespaceFolder
>   - Added support for setting target referral status (TargetState) - fixes [Issue #96](https://github.com/dsccommunity/DFSDsc/issues/96).
> - DFSReplicationGroupMember
> ```

Can you also mention in here the change that Ensure parameter is no longer Mandatory and defaults to 'Present'.
___
*[`CHANGELOG.md` line 26 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9V-Bv40DemjUSKuNw:-NP9V-Bv40DemjUSKuNx:by6u731) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/CHANGELOG.md#L26)):*
> ```Markdown
>   - Allow Get-TargetResource and Test-TargetResource to run if group does not exist - fixes [Issue #125](https://github.com/dsccommunity/DFSDsc/issues/125).
> - DFSReplicationGroupMembership
>   - Add support for setting EnsureEnabled, MinimumFileStagingSize, ConflictAndDeletedQuotaInMB, RemoveDeletedFiles and DfsnPath.
> ```

Can you also mention in here the change that Ensure parameter is no longer Mandatory and defaults to 'Present'.
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 122 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9SJFM9RyzJJ11KW3T:-NP9SJFM9RyzJJ11KW3U:b-havw4k) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L122)):*
> ```PowerShell
>     for each member. These may also be defined separately through the
>     DFSReplicationGroupMember resource. If an FQDN name is used and
>     the DomainName parameter is set, the FQDN domain name must match.
> ```

Can you explicitly state here that if these are defined here then the DFSReplicationGroupMember resource should not under any circumstances be used in the same config (risk of config flappging)?
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 509 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9Sh4z5dReZQB81R_6:-NP9Sh4z5dReZQB81R_7:b-havw4k) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L509)):*
> ```PowerShell
>     A list of computers that are members of this Replication Group.
>     These can be specified using either the ComputerName or FQDN name
>     for each member. These may also be defined separately through the
> ```

Can you explicitly state here that if these are defined here then the DFSReplicationGroupMember resource should not under any circumstances be used in the same config (risk of config flappging)?
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 621 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9QhzAAlaRLcQMjtI8:-NP9QhzB2cvtrysT_z4n:b47ordn) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L621)):*
> ```PowerShell
> 
>             # Get the members (if any were passed in the array)
>             if ($Members)
> ```

Can you use the `$PSBoundParameters.ContainsKey('Members')` check instead (I should have done this throughout)? This is because we actually want this to fire if an empty array is passed.

I really should have broken this out into its own function (but don't worry about that now - just for future note to myself - if I ever get time).
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 755 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9S7Qw07d7NXRchDPw:-NP9S7Qw07d7NXRchDPx:b-x9fuhw) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L755)):*
> ```PowerShell
> 
>             # If any members were passed in the array
>             if ($Members)
> ```

Can you use the `$PSBoundParameters.ContainsKey('Members')` check instead?
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.schema.mof` line 7 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9SkA19DS5yP2lQgoL:-NP9SkA19DS5yP2lQgoM:b-havw4k) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.schema.mof#L7)):*
> ```
>     [Write, Description("Specifies whether the DFS Replication Group should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
>     [Write, Description("A description for the DFS Replication Group.")] String Description;
>     [Write, Description("A list of computers that are members of this Replication Group. These can be specified using either the ComputerName or FQDN name for each member. These may also be defined separately through the DFSReplicationGroupMember resource. If an FQDN name is used and the DomainName parameter is set, the FQDN domain name must match.")] String Members[];
> ```

Can you explicitly state here that if these are defined here then the DFSReplicationGroupMember resource should not under any circumstances be used in the same config (risk of config flappging)?
___
*[`source/DSCResources/DSC_DFSReplicationGroupConnection/DSC_DFSReplicationGroupConnection.psm1` line 512 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9T55N4AWkLUgB0SlB:-NP9T55N4AWkLUgB0SlC:bzaviqu) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroupConnection/DSC_DFSReplicationGroupConnection.psm1#L512)):*
> ```PowerShell
>             } # if
> 
>             if (($EnsureCrossFileRDCEnabled -eq 'Enabled') `
> ```

Could this be simplified down to:
```powershell
if (($PSBoundParameters('EnsureCrossFileRDCEnabled') `
    -and $EnsureCrossFileRDCEnabled -ne $replicationGroupConnection.CrossFileRDCEnabled)
```
___
*[`source/DSCResources/DSC_DFSReplicationGroupMember/README.md` line 5 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9U2I130rkIoUL47Vs:-NP9U2I130rkIoUL47Vt:bhw4shk) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroupMember/README.md#L5)):*
> ```Markdown
> This resource is used to create, edit or remove Replication Group Members. It can be
> used to add members to a Replication Group individually instead of using the Members
> setting in the DFSReplicationGroup.
> ```

Can you add an explicit warning in here that you should only use this resource if the ReplicationGroup.Members is not passed - otherwise config flapping may occur. We generally try to do everything we can do to avoid this, which is why it's fairly rare to allow multiple resources to configure the same settings.
___
*[`source/Examples/Resources/DFSNamespaceFolder/2-DFSNamespaceFolder_Domain_SingleTarget_Config.ps1` line 73 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9Vnds5x1H53pIxxnE:-NP9Vnds5x1H53pIxxnF:b-vurx2d) ([raw file](h [...]

2023-03-10 15:28 UTC, Borgquite reviewed
Sure, will bear that in mind! Thanks for your patience.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-:-NQAryJ9Bgi9yaylQPfd:b83czjz)* status: 33 of 76 files reviewed, 35 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 16 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9QD3Z2posvv2703Dy:-NQAtBla5L3jfpn6hKEK:b-mog0iw) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/CHANGELOG.md#L16)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you also mention in here the change that Ensure parameter is no longer Mandatory and defaults to 'Present'.
</blockquote></details>

Done. This was present under 'All Modules' - but you're right, they don't all use it. Now updated
___
*[`CHANGELOG.md` line 26 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9V-Bv40DemjUSKuNw:-NQAukNV3RbPcsMHlJrm:bs7wumb) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/CHANGELOG.md#L26)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you also mention in here the change that Ensure parameter is no longer Mandatory and defaults to 'Present'.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 122 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9SJFM9RyzJJ11KW3T:-NQAw5Xg6NAwLSYCLgEQ:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L122)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you explicitly state here that if these are defined here then the DFSReplicationGroupMember resource should not under any circumstances be used in the same config (risk of config flappging)?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 509 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9Sh4z5dReZQB81R_6:-NQAwH2f5b37pk1YWzWf:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L509)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you explicitly state here that if these are defined here then the DFSReplicationGroupMember resource should not under any circumstances be used in the same config (risk of config flappging)?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 621 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9QhzAAlaRLcQMjtI8:-NQAx0xy82CzeLuRkRjY:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L621)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use the `$PSBoundParameters.ContainsKey('Members')` check instead (I should have done this throughout)? This is because we actually want this to fire if an empty array is passed.

I really should have broken this out into its own function (but don't worry about that now - just for future note to myself - if I ever get time).
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 755 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9S7Qw07d7NXRchDPw:-NQAx7yX-ZTdu74uKlJa:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L755)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use the `$PSBoundParameters.ContainsKey('Members')` check instead?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.schema.mof` line 7 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9SkA19DS5yP2lQgoL:-NQAwVOXBXAmFjFK6zXh:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.schema.mof#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you explicitly state here that if these are defined here then the DFSReplicationGroupMember resource should not under any circumstances be used in the same config (risk of config flappging)?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroupConnection/DSC_DFSReplicationGroupConnection.psm1` line 512 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9T55N4AWkLUgB0SlB:-NQAyoYF8HEfqrSsHFYO:b-twjboy) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroupConnection/DSC_DFSReplicationGroupConnection.psm1#L512)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could this be simplified down to:
```powershell
if (($PSBoundParameters('EnsureCrossFileRDCEnabled') `
    -and $EnsureCrossFileRDCEnabled -ne $replicationGroupConnection.CrossFileRDCEnabled)
```
</blockquote></details>

I'm not sure. Check the code above - it's a copy/paste of EnsureRDCEnabled. In that variable, inside the DSC module it's a string 'Enabled' but the underlying Get-DFSReplicationGroup returns a boolean ($true/$false). Not sure why it's not just boolean throughout but just trying to keep the setting in line with how the module works at present.
___
*[`source/DSCResources/DSC_DFSReplicationGroupMember/README.md` line 5 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9U2I130rkIoUL47Vs:-NQB-3tjBJ4u1hDah7jX:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroupMember/README.md#L5)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add an explicit warning in here that you should only use this resource if the ReplicationGroup.Members is not passed - otherwise config flapping may occur. We generally try to do everything we can do to avoid this, which is why it's fairly rare to allow multiple resources to configure the same settings.
</blockquote></details>

Done.
___
*[`source/Examples/Resources/DFSNamespaceFolder/2-DFSNamespaceFolder_Domain_SingleTarget_Config.ps1` line 73 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9Vnds5x1H53pIxxnE:-NQB-S3h7en1JZCAP2Np:bdygjo1) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/Examples/Resources/DFSNamespaceFolder/2-DFSNamespaceFolder_Domain_SingleTarget_Config.ps1#L73)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Given the `TargetState` defaults to 'Online', do we need to update this example? Or am I getting confused?
</blockquote></details>

Yeah, this is a legacy of #97 - you're right, these aren't really necessary in the examples. I've removed all the 'Online' entries - only the 'Offline' ones remain. Done.
___
*[`source/Examples/Resources/DFSNamespaceFolder/2-DFSNamespaceFolder_Domain_SingleTarget_Config.ps1` line 84 at r8](https://reviewable.io/reviews/dsccommunity/DFSDsc/126#-NP9W0Va4z1P7nDzaPwo:-NQB0gYpDAK_ZJAoRF1I:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/Examples/Resources/DFSNamespaceFolder/ [...]

2023-03-10 16:00 UTC, Borgquite reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126)* status: 33 of 76 files reviewed, 35 unresolved discussions (waiting on @PlagueHO)

___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 621 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9QhzAAlaRLcQMjtI8:-NQBEPDq4KN2XL7jWyST:bvqncj9) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L621)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry - I tried this but it broke the tests in a way that I don't really understand. It seems to work in produciton - is this the end of the world?
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 755 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9S7Qw07d7NXRchDPw:-NQBF1-X2j57MC7a64uk:bir77oz) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L755)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See followup above.


<!-- Sent from Reviewable.io -->

2023-03-30 16:02 UTC, Borgquite commented
@PlagueHO Still waiting on this one :)

2023-04-16 05:57 UTC, PlagueHO commented
Sorry about the delay @Borgquite - will continue with this, this week.

2023-04-28 10:50 UTC, Borgquite reviewed
Any progress? :)

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-:-NU6U-BN084XLNmBviTA:b9dgapi)* status: 33 of 76 files reviewed, 35 unresolved discussions (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2023-05-03 04:05 UTC, PlagueHO commented
Hi @Borgquite - Am so sorry for the delay. Have been so slammed in my day job. I've blocked time this weekend. It will happen.

2023-07-10 17:11 UTC, Borgquite commented
@PlagueHO Another gentle poke here - so I can honour your time and not keep pestering you, do you have any idea when this might be done? Thanks!

2023-07-11 06:33 UTC, PlagueHO requested changes
Awesome @Borgquite - sorry this took so long. Just some really minor tweaks then merge. I think we'll probably leave the if ($Member) one if we can just note the behaviour in the README.md for that particular resource as I don't see it very common to want to remove all members from an RG.

> Reviewed 15 of 27 files at r9, 18 of 18 files at r10, 9 of 9 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-:-N_2da9jAiX9aeSFtlji:bz6dpe9)* status: all files reviewed, 3 unresolved discussions (waiting on @Borgquite)

___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 621 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9QhzAAlaRLcQMjtI8:-N_2NJli2ox6QoEmhjRe:b-8ha5im) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L621)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Sorry - I tried this but it broke the tests in a way that I don't really understand. It seems to work in produciton - is this the end of the world?
</blockquote></details>

Using a ```$PSBoundParameters.ContainsKey('Members')``` check is usually best when there needs to be a behavior difference between not passing the parameter at all and passing null/empty array. In this code, both permutations will behave in the same way - so there will be no combination of parameters that can be used to set the replication group to have no members.

Is there a situation where you would want to clear out all the members from a replication group? This is an edge case, but it's more a question of what behavior would you expect if you had two configs:



```powershell
# The RG should have no members in it
DFSReplicationGroup RemoveAllMembers {
    GroupName = 'rg1'
    Members = @()
}
```
Compared with

```powershell
# The members of the RG should not be considered at all
DFSReplicationGroup IgnoreCurrentMembers {
    GroupName = 'rg1'
}
```

When using ```if ($Members)``` then both configs will always behave like the second config.

It is a subtle nuance and probably not likely to be a concern for most users, but it's a pattern we try to support if we can.

What were the strange issues with the tests that occurred? Could have been our tests weren't the best. :cry:

But perhaps we document this in the README.MD for the resource that you can't have a RG with no members by configuring it this way?
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 755 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9S7Qw07d7NXRchDPw:-N_2Qc8mCvETNV3MG2zT:b-34vmyd) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L755)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

See followup above.
</blockquote></details>

See above
___
*[`source/DSCResources/DSC_DFSReplicationGroupConnection/DSC_DFSReplicationGroupConnection.psm1` line 512 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9T55N4AWkLUgB0SlB:-N_2cPGt0H91nb5fFAUR:b-r9t87g) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroupConnection/DSC_DFSReplicationGroupConnection.psm1#L512)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

I'm not sure. Check the code above - it's a copy/paste of EnsureRDCEnabled. In that variable, inside the DSC module it's a string 'Enabled' but the underlying Get-DFSReplicationGroup returns a boolean ($true/$false). Not sure why it's not just boolean throughout but just trying to keep the setting in line with how the module works at present.
</blockquote></details>

Let's just leave it as is. 
___
*[`source/Examples/Resources/DFSNamespaceFolder/1-DFSNamespaceFolder_Domain_MultipleTarget_Config.ps1` line 23 at r12](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-N_2cqqvAkjNHs9ePY_1:-N_2cqqvAkjNHs9ePY_2:bb70wkm) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/c00f2168464675771381566caa924bc9bf50236d/source/Examples/Resources/DFSNamespaceFolder/1-DFSNamespaceFolder_Domain_MultipleTarget_Config.ps1#L23)):*
> ```PowerShell
>     .DESCRIPTION
>         Create an AD Domain V2 based DFS namespace called software in the domain contoso.com with
>         a four targets on the servers ca-fileserver, ma-fileserver, ny-fileserver01 and ny-filerserver02. It also
> ```

Nit:



_Suggestion:_
```PowerShell
        four targets on the servers ca-fileserver, ma-fileserver, ny-fileserver01 and ny-filerserver02. It also
```


<!-- Sent from Reviewable.io -->

2023-07-11 12:59 UTC, Borgquite reviewed
@PlagueHO Right - I've made the changes requested including managing to fix the dodgy tests. Let me know :)

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-:-N_419OM2Xlg_Ih5cSGN:bgx8yui)* status: 72 of 76 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 621 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9QhzAAlaRLcQMjtI8:-N_3xX_CBHXWwy5-qZqX:b-lnt22u) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L621)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Using a ```$PSBoundParameters.ContainsKey('Members')``` check is usually best when there needs to be a behavior difference between not passing the parameter at all and passing null/empty array. In this code, both permutations will behave in the same way - so there will be no combination of parameters that can be used to set the replication group to have no members.

Is there a situation where you would want to clear out all the members from a replication group? This is an edge case, but it's more a question of what behavior would you expect if you had two configs:



```powershell
# The RG should have no members in it
DFSReplicationGroup RemoveAllMembers {
    GroupName = 'rg1'
    Members = @()
}
```
Compared with

```powershell
# The members of the RG should not be considered at all
DFSReplicationGroup IgnoreCurrentMembers {
    GroupName = 'rg1'
}
```

When using ```if ($Members)``` then both configs will always behave like the second config.

It is a subtle nuance and probably not likely to be a concern for most users, but it's a pattern we try to support if we can.

What were the strange issues with the tests that occurred? Could have been our tests weren't the best. :cry:

But perhaps we document this in the README.MD for the resource that you can't have a RG with no members by configuring it this way?
</blockquote></details>

OK - now that I understand that I was able to fix the test (which was passing $null for Members and testing as though it was undefined).

Should be hopefully all good now :)
___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 755 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9S7Qw07d7NXRchDPw:-N_3xkfz-qtlmiB6D3Dj:be2a9gl) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L755)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

See above
</blockquote></details>

See above - should be all good now :)
___
*[`source/Examples/Resources/DFSNamespaceFolder/1-DFSNamespaceFolder_Domain_MultipleTarget_Config.ps1` line 23 at r12](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-N_2cqqvAkjNHs9ePY_1:-N_3hlWJE7saTlb7_cqg:banhqor) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/c00f2168464675771381566caa924bc9bf50236d/source/Examples/Resources/DFSNamespaceFolder/1-DFSNamespaceFolder_Domain_MultipleTarget_Config.ps1#L23)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nit:
</blockquote></details>

All done (also had the same error in DFSNamespaceRoot example)


<!-- Sent from Reviewable.io -->

2023-07-24 11:24 UTC, Borgquite commented
@PlagueHO Just checking you got the notification above. Hopefully this is quick to resolve now! :)

2023-08-03 11:33 UTC, Borgquite commented
@PlagueHO Let me know how it's going :)

2023-08-03 21:06 UTC, PlagueHO approved these changes
Sorry @Borgquite - I missed the first notification :cry: But now...

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Thank you so much for the patience!

Lets see if the deploy pipeline works (API keys sometimes expire :grin: but I'll get those fixed if they have).

> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-:-NaxD14v7JsTpGwfligi:bv85dcn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Borgquite)

___
*[`source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1` line 621 at r8](https://reviewable.io/reviews/dsccommunity/dfsdsc/126#-NP9QhzAAlaRLcQMjtI8:-NaxCp1d9Da2DsXCl-nZ:b9bkkp1) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/18d3906fb57de8fb35a911a6ddc97d286161d47a/source/DSCResources/DSC_DFSReplicationGroup/DSC_DFSReplicationGroup.psm1#L621)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

OK - now that I understand that I was able to fix the test (which was passing $null for Members and testing as though it was undefined).

Should be hopefully all good now :)
</blockquote></details>

Looks great!


<!-- Sent from Reviewable.io -->

2023-08-03 21:07 UTC, merged

2023-08-09 12:16 UTC, Borgquite commented
@PlagueHO Fear the deploy pipeline may have that API key issue...

https://dev.azure.com/dsccommunity/DFSDsc/_build/results?buildId=8075&view=results

2023-08-09 12:41 UTC, gaelcolas commented
Yep, he asked me to update, will do in a few hours (my evening).

2023-08-10 05:01 UTC, gaelcolas commented
DFSDsc 5.0.0-preview0001 has been published to the PSGallery: https://www.powershellgallery.com/packages/DFSDsc/5.0.0-preview0001

2023-08-10 11:12 UTC, Borgquite commented
@gaelcolas Great! I've just downloaded and deployed & seems to be working fine. What's the normal process & timeframe for moving from prerelease to full release, just so I know?

2023-08-10 11:16 UTC, Borgquite commented
@gaelcolas (Presume you're also aware that the build is still reporting errors?) https://dev.azure.com/dsccommunity/DFSDsc/_build/results?buildId=8082&view=logs&j=5d0a9c4e-8741-5118-af45-406a30fe661c&t=bda0b158-a237-516f-c1d0-31339587c5b5

2023-08-10 20:28 UTC, PlagueHO commented
I'm just checking this now. @Borgquite - we'll give the preview release a couple of weeks and if no major issues we'll push a release build.

2023-08-10 20:32 UTC, PlagueHO commented
Oh, the issue is that this build has already been pushed. Think it's just had two deployments running for some reason. This should be fixed when we push a release build.

2023-08-14 12:10 UTC, Borgquite commented
@PlagueHO OK - is this an issue though? (Attempt 1 failed with 'Bad credentials' accessing docs.github.com)
![image](https://github.com/dsccommunity/DFSDsc/assets/53898223/9d4b39c6-f24c-44d9-bda7-6cedaa69c703)
https://dev.azure.com/dsccommunity/DFSDsc/_build/results?buildId=8082&view=logs&j=5d0a9c4e-8741-5118-af45-406a30fe661c&t=bda0b158-a237-516f-c1d0-31339587c5b5&s=d4a9a205-d52e-57fb-7b17-15a9d984af62

Only mention it in case it breaks the release build too. The doco is currently still showing the older preview https://github.com/dsccommunity/DFSDsc/wiki

2023-08-16 22:51 UTC, PlagueHO commented
Hmm might need to update the GitHub API key too @gaelcolas :D

2023-08-17 05:16 UTC, gaelcolas commented
Hmmm, GitHub changed something about auth and/or token expired, gotta look into that.

2023-08-29 16:52 UTC, Borgquite commented
Any movement on this @PlagueHO @gaelcolas ?
Hoping the GitHub issue can be fixed & the release build deployed :) Thanks!

2023-08-30 06:15 UTC, PlagueHO commented
Hmm. I'll connect with @gaelcolas offline and see if we can figure this out - might be this weekend though... :(

2023-09-01 07:07 UTC, PlagueHO commented
@Borgquite - v5.0.0 has gone out. Thank you for all your help!